max_chain_length: 3

llm:
  temperature: 0.6
  max_tokens: 8000
  model_name: "gpt-3.5-turbo"
  streaming: true
  timeout: 300
  presence_penalty: 0.1
  frequency_penalty: 0.1
  top_p: 1.0
  verbose: true

search_enabled: false

prompts:
  web_search_prompt: "web_search_prompt.j2"
  dice_processing_prompt: "dice_processing_prompt.j2"
  ai_writer_prompt: "ai_writer_prompt.j2"
  storyboard_generation_prompt: "storyboard_generation_prompt.j2"
  storyteller_gm_prompt: "ai_writer_prompt_storyteller.j2" # New prompt for Storyteller GM
  director_prompt: "director_prompt.j2"
  character_prompt: "character_prompt.j2"
  lore_prompt: "lore_prompt.j2"
  puzzle_prompt: "puzzle_prompt.j2"
  default_writer_prompt: "ai_writer_prompt.j2" # Explicit key for default writer
  todo_prompt: "todo_prompt.j2"
  persona_classifier_prompt: "persona_classifier_prompt.j2"
  therapist_writer_prompt: "therapist_writer_prompt.j2"
  coder_writer_prompt: "coder_writer_prompt.j2"
  secretary_writer_prompt: "secretary_writer_prompt.j2"
  secretary_todo_prompt: "secretary_todo_prompt.j2"
  lore_knowledge_prompt: "lore_knowledge_prompt.j2"

image_generation_payload:
  url: "http://192.168.1.4:7860"
  steps: 30
  sampler_name: "Euler"
  scheduler: "Simple"
  cfg_scale: 3.5
  distilled_cfg_scale: 1.0
  hr_cfg: 3.5
  hr_distilled_cfg: 1.0
  width: 512
  height: 512
  hr_scale: 2
  hr_upscaler: "SwinIR 4x"
  denoising_strength: 0.6
  hr_second_pass_steps: 10
  negative_prompt: ""

timeouts:
  image_generation_timeout: 180

refusal_list:
  - "I'm not able"
  - "I am not able"
  - "I'm afraid I can't"
  - "I am afraid I can't"
  - "I'm afraid I can not"
  - "I am afraid I can not"
  - "I can't"
  - "I can't"
  - "I cant"
  - "I can not"
  - "I cannot"
  - "I'm sorry"
  - "I am sorry"
  - "I'm really sorry"
  - "I am really sorry"
  - "I understand"
  - "I'm unable"
  - "I am unable"
  - "I'm not going to"
  - "I am not going to"
  - "I'm not comfortable"
  - "I am not comfortable"
  - |
    **Game Master**: Hello! What kind of story would you like to create today?

defaults:
  db_file: "chainlit.db"

dice:
  sides: 20  # Default number of sides for /roll

knowledge_directory: "./knowledge"

image_settings:
  num_image_prompts: 1

agents:
  decision_agent:
    temperature: 0.2
    max_tokens: 100
    streaming: true
    verbose: true
    base_url: "http://192.168.1.111:5000/v1"
    tools:
      dice_roll:
        sides: 20
      web_search:
        enabled: true
  writer_agent:
    base_url: "http://192.168.1.111:5000/v1"
    temperature: 0.7
    max_tokens: 8000
    streaming: true
    verbose: true
    personas:
      "Storyteller GM":
        prompt_key: "storyteller_gm_prompt"
      "Therapist":
        prompt_key: "therapist_writer_prompt"
      "Coder":
        prompt_key: "coder_writer_prompt"
      "Secretary":
        prompt_key: "secretary_writer_prompt"
      "Default":
        prompt_key: "default_writer_prompt"
  todo_agent:
    personas:
      "Secretary":
        prompt_key: "secretary_todo_prompt"
  knowledge_agent:
    personas:
      "Lorekeeper":
        prompt_key: "lore_knowledge_prompt"
  storyboard_editor_agent:
    base_url: "http://192.168.1.111:5000/v1"
    temperature: 0.7
    max_tokens: 8000
    streaming: false
    verbose: true

storyboard_generation_prompt_prefix: "masterpiece, best quality, amazing quality"  # Add this line
storyboard_generation_prompt_postfix: ""  # Add this line

search:
  serpapi_key: ""

openai:
  base_url: "http://192.168.1.111:5000/v1"
  api_key: ""

logging:
  level: "INFO"
  file: "chainlit.log"
  console: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10MB
  backup_count: 3

paths:
  storage: "public/storage"
  knowledge: "knowledge"  # No leading/trailing slashes
  db: "chainlit.db"

error_handling:
  max_retries: 3
  retry_delay: 5
  log_level: "ERROR"

api:
  base_url: "http://localhost:8080"
  timeout: 30
  max_connections: 10

features:
  image_generation: true
  web_search: true
  dice_rolling: true

rate_limits:
  image_generation: "5/minute"
  api_calls: "60/hour"

security:
  secret_key: "your-secret-key-here"
  session_timeout: 3600

monitoring:
  enabled: false
  endpoint: "http://localhost:9411"
  sample_rate: 0.1

caching:
  enabled: true
  ttl: 3600
  max_size: "100MB"

chainlit:
  project_name: "Dreamdeck"
  db: "sqlite:///./chainlit.db"

chat:
  start_message: "Hello! What kind of story would you like to create today?"
