name: Dreamdeck CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and start services with Docker Compose
      run: docker-compose up -d --build

    - name: Wait for app to be ready
      run: |
        for i in {1..30}; do
          if docker-compose logs dreamdeck | grep -q "Dreamdeck app loaded"; then
            echo "App is ready!"
            break
          fi
          echo "Waiting for app to be ready..."
          sleep 5
        done

    - name: Run tests in Docker
      run: docker-compose exec -T dreamdeck make docker-test

    - name: Lint with flake8 in Docker
      run: docker-compose exec -T dreamdeck poetry run flake8 . tests/

    - name: Check formatting with black in Docker
      run: docker-compose exec -T dreamdeck poetry run black --check . tests/
