name: Dreamdeck CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install Poetry export plugin
      run: poetry self add poetry-plugin-export

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock', '**/pyproject.toml') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies via pip
      run: |
        # Export dependencies including dev group to requirements.txt
        poetry export --with dev --format requirements.txt --output requirements.txt
        # Install using pip into the Python environment set up by actions/setup-python
        pip install -r requirements.txt

    - name: Run tests
      # Run pytest directly; PYTHONPATH is still needed for src imports
      run: PYTHONPATH=. pytest --tb=short tests/smoke tests/integration --cov=src --cov-report term-missing

    - name: Check formatting with black
      # Run black directly
      run: black --check . tests/
